export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const ACCOUNT_DELETED = 'ACCOUNT_DELETED';

export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_ALL_PRODUCTS = 'GET_ALL_PRODUCTS';
export const CLEAR_PRODUCTS = 'CLEAR_PRODUCTS';
export const SHOW_DELETE_ITEM_MODAL = 'SHOW_DELETE_ITEM_MODAL';
export const HIDE_DELETE_ITEM_MODAL = 'HIDE_DELETE_ITEM_MODAL';
export const SET_LOADING_TRUE = 'SET_LOADING_TRUE';

export const SHOW_ADD_ITEM_FORM = 'SHOW_ADD_ITEM_FORM';
export const HIDE_ADD_ITEM_FORM = 'HIDE_ADD_ITEM_FORM';

export const SHOW_DELETE_PRODUCT_MODAL = 'SHOW_DELETE_PRODUCT_MODAL';
export const HIDE_DELETE_PRODUCT_MODAL = 'HIDE_DELETE_PRODUCT_MODAL';

export const ADD_PRODUCT_CART = 'ADD_PRODUCT_CART';
export const REMOVE_PRODUCT_CART = 'REMOVE_PRODUCT_CART';
export const CLEAR_CART = 'CLEAR_CART';

export const SET_CLIENT_SECRET = 'SET_CLIENT_SECRET';
export const CLEAR_CLIENT_SECRET = 'CLEAR_CLIENT_SECRET';
